#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6504355410                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ru                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
# playstore_link                            :                                           # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Color Palette app creates unique color palettes based on the shades you choose.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Den Dmitriev                                
your_link                                 : https://github.com/DenDmitriev                   
your_city                                 : Moscow                                
email_address                             : dv.denstr@gmail.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
github_username                           : DenDmitriev
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create a palette of colors
    description                           : Extract stunning shades directly from your photos and enjoy the amazing combinations created by nature.
    fontawesome_icon_name                 : plus
    
  - title                                 : Color Hunt Color Library
    description                           : Easily find the right shades using keywords and add your favorite palettes to your personal catalog.
    fontawesome_icon_name                 : search

  - title                                 : Color picker
    description                           : Use the HSL, RGB, Lab, CMYK and Hex color systems to achieve excellent results.
    fontawesome_icon_name                 : eye-dropper

  - title                                 : Checking the contrast
    description                           : Improve the quality of your work with our unique shade contrast check system.
    fontawesome_icon_name                 : adjust

  - title                                 : Edit the colors
    description                           : Transform your palette with our intuitive editor.
    fontawesome_icon_name                 : palette
  
  - title                                 : Export the palette
    description                           : Easily share your shades through images or HTML/XML codes.
    fontawesome_icon_name                 : share


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
